### PR TITLE
Update third party licenses

### PR DESCRIPTION
**Pull request by cwelton**
1. Remove unused LAPACK license
2. Per advisement from legal use the GPL2 rather than LGPL3 license for Eigen
3. Remove the now unused LGPL3 license.
4. Add paragraph from legal to the Eigen license information.

### CODE REVIEW

**Comment by cwelton** [comment]
Florian, please let me know asap if this looks good to you so we can merge it in.  Thanks.

**Comment by fschopp** [comment]
I will merge this manually as opposed to pulling, because of the misleading 'merge fetch_head' commit.

**Comment by fschopp** [comment]
Merged with commit cecb9c7.

**Comment by cwelton** [comment]
Apologies on that, my perforce experience has muddled my git usage.

**Pull request closed without merging**
