### PR TITLE
Fixed null values in the results of naive Bayes

### PR DESCRIPTION
**Pull request by farzadras**
Jira: MADLIB-523

This fix addresses the issue of NULL values which stemmed from attribute values in testing data set that cannot be found in training data set.

### CODE REVIEW

**Comment by iyerr3** [comment]
Code review completed with Farzad - the code and logic looks fine. Pending install-check tests.

**Comment by iyerr3** [comment]
@farzadras Please update the initial comment in changed file to reflect that NULL values are no more created for each (key, class) pair (as discussed in our review). The code could also use short inline comments on the logic for each nested subquery.

**Comment by iyerr3** [comment]
@farzadras Please place a comment here after you have updated this with your latest changes (including change in comments).

**Comment by farzadras** [comment]
Sure. There is a new data set that I am looking into before finalizing this pull request.

**Comment by farzadras** [comment]
Updates: Tested with the new data set. Removed the comment about NULL values in code.

**Comment by iyerr3** [comment]
Code merged: https://github.com/madlib/madlib/commit/d7cd128595f980c1ef283c740947d8c8638e9876

**Pull request closed without merging**
