### PR TITLE
fix madlib 690

### PR DESCRIPTION
**Pull request by renyi533**
With madlib 677, we only addressed the issue for training. In this pull request, we corrected the classification issue.

### CODE REVIEW

**Comment by iyerr3** [comment]
Is this ready for merge?

**Comment by fschopp** [comment]
This will definitely need a rebase as it contains a merge commit.

**Comment by iyerr3** [comment]
Whwn I rebase I lose the first commit (https://github.com/renyi533/madlib/commit/d456f43937fe7433641bdc57a165de6aaa4504fa) which seems to be similar to (https://github.com/madlib/madlib/commit/fa39795c2b3bf52f0b985570b347ae195677a959) in the history. Is that the expected output? Does Git see that the same commit occurs in different branches?

**Comment by fschopp** [comment]
Hard to answer without seeing the git command that you are using. Could you post that?

**Comment by iyerr3** [comment]
git co -b madlib-677 yi_ren/madlib_677
git rebase origin master

(origin master at same state as upstream master)

**Comment by iyerr3** [comment]
Pull request completed: https://github.com/madlib/madlib/commit/720cc0e736ec89e823eda6acf4cf0b69b04b5cd1

**Pull request closed without merging**
