### PR TITLE
Multinomial logistic: Fix MADLIB-665

### PR DESCRIPTION
**Pull request by walkingsparrow**
Multinomial logistic regression: Added variable number limitation to documentation

Jira: MADLIB-665

In multinomial logistic regression, the number of independent variables cannot
exceed 65535. This limitation was added to the usage section of the
documentation.

### CODE REVIEW

**Comment by cwelton** [comment]
Looks good to me.   Rahul can you perform the merge?

**Comment by fschopp** [comment]
Please combine into one commit before merging.

_Update_ Never mind, I just saw the two commits address very different issues.

**Comment by cwelton** [comment]
Yup if anything this should be two separate pull requests for the two different issues instead of having the two commits merged.

**Comment by iyerr3** [comment]
Closing since this is superseded by https://github.com/madlib/madlib/pull/244

**Pull request closed without merging**
