### PR TITLE
Build System: Replace GREENPLUM macro, take 2

### PR DESCRIPTION
**Pull request by haradh1**
Jira: MADLIB-666

### CODE REVIEW

**Comment by cwelton** [comment]
Looks good!   If this get's everything can we remove the historical GREENPLUM macro definition as well?

**Comment by fschopp** [comment]
Hmm, the old definition of GREENPLUM had already been removed with commit 7f82cab. Interesting that it worked at all.

**Comment by haradh1** [comment]
Most of the case were for the better performance in GPDB.

**Comment by fschopp** [comment]
I think you forgot to the m4_include(`SQLCommon.m4')

**Comment by haradh1** [comment]
In which file?

**Pull request merged**
