### PR TITLE
DT Test: Removed use of madlib schema for test

### PR DESCRIPTION
**Pull request by iyerr3**
Jira: MADLIB-684

There is no need to use a temporary table for
test results since a temporary schema is created
before the test starts. Further, any DB object
should be created w/o schema prefix, since the
test is executed in the temporary schema context.
Drop statements should also be avoided since the
default schema will be cleaned outside.

Other changes:
- Removed all trailing whitespace characters. 
  Trailing whitespace should be removed since it 
  adds unnecessary diff lines in the commit.

### CODE REVIEW

**Comment by cwelton** [comment]
Looks good to me.  Should be safe for merging.

**Comment by fschopp** [comment]
There is no need to create temporary tables in the unit tests, as unit tests are run with a temporary schema first in the `search_path`.

However, creating tables in the MADlib schema is always a bad idea. The DT unit tests still do that.

**Comment by fschopp** [comment]
While we are at it, the DT unit tests should probably be fixed in the sense of my previous comment.

**Comment by iyerr3** [comment]
@fschopp Please check if this is per the rules. The three commits will be melded before merge, but I wanted to run this by you quickly. There are still create functions statements that use madlib schema, as well as some tables for checking for the results. Do you suggest I remove those as well?

**Comment by fschopp** [comment]
I'd say it's fine for now, though at some point the testing should be moved out of the pgsql functions and performed in plain SQL.

**Comment by iyerr3** [comment]
Will appreciate someone testing this with PG 9.2 and GP to ensure nothing got broken. ( @cwelton Hoping you could assign this to someone with open cycles)

**Comment by iyerr3** [comment]
@cwelton Should I go ahead with the merge on this?

**Comment by cwelton** [comment]
Good to merge.

**Comment by iyerr3** [comment]
Merged with commit: https://github.com/madlib/madlib/commit/6f61346486dcf3f05e9442be470362cb7e30089d

**Pull request closed without merging**
