### PR TITLE
UDF that mimicks CREATE TABLE AS. Workaround for MADLIB-241

### PR DESCRIPTION
**Pull request by fschopp**
_The_ workaround. Please pull me!

### CODE REVIEW

**Comment by agorajek** [comment]
Florian, did you forget a test script or did not make one on purpose?

FYI: I can add one...

**Comment by fschopp** [comment]
That's an oversight. Yes, please add a test. Thanks!

**Comment by fschopp** [comment]
We should clearly document that this is a workaround (Action item, just added to the MADLIB-241), which is not meant to be used without need. Whenever possible, using standard SQL is preferred. Beyond that, I don't think there is anything else we can do. Running a count(*) would just take as long as creating the table itself, wouldn't it?

**Comment by agorajek** [comment]
Yeah, I think that we should only advise on using this workaround UDF, rather that add some check that would slow it down.

**Pull request merged**
