### PR TITLE
Cast of float array to sparse vector cannot handle null values

### PR DESCRIPTION
**Pull request by aojwang**
Cast of float array to sparse vector cannot handle null values.
Jira: http://jira.madlib.net/browse/MADLIB-282.

### CODE REVIEW

**Comment by cwelton** [comment]
Hitoshi, can you put together a version of this patch using makeInplaceSparseData per your suggestion?

Thanks.

**Comment by cwelton** [comment]
Test: Hitoshi, are you getting notifications?

**Comment by haradh1** [comment]
Hmm, I'm not getting notification even after joining madlib today...

**Comment by haradh1** [comment]
It turned out I was wrong, makeInplaceSparseData is not appropriate here. Though I sent out PR111, it might be better to merge this fix and put off my fix for later release, to make sure it is correct.

**Comment by fschopp** [comment]
Following Hitoshi's recommendation of pulling #81 and leaving pull request #111 for later.

**Pull request merged**
