### PR TITLE
The bug that broke the unit tests fixed

### PR DESCRIPTION
**Pull request by yuj18**
I accidentally commented out "plpy.execute('drop table svm_temp_result'); " in svm_classification() in
online_sv.py_in. That broke the install-check. The bug has been fixed:

madpack -p greenplum -c yuj18@$HOSTNAME:5432/madlib_test install-check
TEST CASE RESULT|Module: array_ops|array_ops.sql_in|PASS|Time: 38 milliseconds
TEST CASE RESULT|Module: bayes|bayes.sql_in|PASS|Time: 1192 milliseconds
TEST CASE RESULT|Module: compatibility|gp_comp.sql_in|PASS|Time: 262 milliseconds
TEST CASE RESULT|Module: plda|plda.sql_in|PASS|Time: 1715 milliseconds
TEST CASE RESULT|Module: quantile|quantile.sql_in|PASS|Time: 155 milliseconds
TEST CASE RESULT|Module: regress|linear.sql_in|PASS|Time: 430 milliseconds
TEST CASE RESULT|Module: regress|logistic.sql_in|PASS|Time: 1475 milliseconds
TEST CASE RESULT|Module: sketch|cm.sql_in|PASS|Time: 7768 milliseconds
TEST CASE RESULT|Module: sketch|fm.sql_in|PASS|Time: 1062 milliseconds
TEST CASE RESULT|Module: sketch|mfv.sql_in|PASS|Time: 253 milliseconds
TEST CASE RESULT|Module: sketch|support.sql_in|PASS|Time: 33 milliseconds
TEST CASE RESULT|Module: svd_mf|svdmf.sql_in|PASS|Time: 2649 milliseconds
TEST CASE RESULT|Module: svec|svec_test.sql_in|PASS|Time: 1936 milliseconds
TEST CASE RESULT|Module: assoc_rules|assoc_rules.sql_in|PASS|Time: 1007 milliseconds
TEST CASE RESULT|Module: conjugate_gradient|conj_grad.sql_in|PASS|Time: 304 milliseconds
TEST CASE RESULT|Module: data_profile|data_profile.sql_in|PASS|Time: 167 milliseconds
TEST CASE RESULT|Module: decision_tree|dec_trees.sql_in|PASS|Time: 2897 milliseconds
TEST CASE RESULT|Module: kmeans|kmeans.sql_in|PASS|Time: 2496 milliseconds
TEST CASE RESULT|Module: kernel_machines|kernel_mach.sql_in|PASS|Time: 6202 milliseconds

### CODE REVIEW

**Comment by cwelton** [comment]
Merged.  A little better, but tests still failing.  I'll take a look at the failures and let you know what it looks like the problem is.

**Comment by cwelton** [comment]
New problem:

```
select madlib.lsvm_predict('lclss', '{10,-20,5,5}') > 0;
psql:/tmp/madlib.Xp_cAu/kernel_machines/test/kernel_mach.sql_in.tmp:52: WARNING:  plpy.SPIError: unrecognized error in PLy_spi_execute_query
CONTEXT:  PL/Python function "lsvm_predict"
psql:/tmp/madlib.Xp_cAu/kernel_machines/test/kernel_mach.sql_in.tmp:52: ERROR:  plpy.SPIError: missing "]" in array dimensions (plpython.c:4700)
LINE 1: SELECT madlib.svm_dot('[1.3961697133085593, -3.9016109074289...
               ^
QUERY:  SELECT madlib.svm_dot('[1.3961697133085593, -3.901610907428926, -0.73575220703296917, -1.0001000100008972]', '[10.0, -20.0, 5.0, 5.0]') /2.00010001 + -1.70583775527 AS sum FROM lclss
CONTEXT:  Traceback (most recent call last):
  PL/Python function "lsvm_predict", line 28, in <module>
    return online_sv.lsvm_predict(MADlibSchema, model_table, ind);
  PL/Python function "lsvm_predict", line 429, in lsvm_predict
PL/Python function "lsvm_predict"
```

**Comment by yuj18** [comment]
I am using Greenplum 4.0, and don't actually run into this error:

select madlib.lsvm_predict('lclss', '{10,-20,5,5}') > 0;
INFO:  ('lsvm_predict: %s', "SELECT
madlib.svm_dot('{1.72531032169723,-2.97662152191821,-0.259054237731663,1.00
010001000091}', '{10,-20,5,5}') /2.00010001 + -1.72660699742 AS sum FROM
lclss")

## ?column?

t
(1 row)

I guess PL/Python installed to Greenplum 4.2 suddenly decides to use
square instead of curly brackets to enclose a string that is converted
from an array. I have revised the code to handle this problem. Please check
out the new commit on Github.

On 12/21/11 7:07 AM, "Caleb Welton"
<reply+i-2609049-411f58d57ba531193662ec0751fb468793cbbda3-1195543@reply.git
hub.com> wrote:

**Comment by cwelton** [comment]
Not just greenplum 4.2, but also Postgres 9.1.  

The difference here is that in 4.1 and 9.0 arrays are passed into python as strings.  In 4.2 and 9.1 arrays are passed into python as lists.

**Pull request merged**
