### PR TITLE
Implementation of support for numeric attributes using Gaussian probability estimate

### PR DESCRIPTION
**Pull request by adirastogi**
These changes add support for using numeric attributes in Naive Bayes classification. The probabilities of theses attributes are calculated using a Gaussian distribution. This branch contains the associated code and documentation changes, as well as unit tests to test the newly added feature.

### CODE REVIEW

**Comment by haying** [comment]
Hi Aditya,

It is impressive that you pull out such a high-quality PR as a first-time contributor. I reviewed it and  found only 2 small issues. I pushed the minor fixes to [here](https://github.com/madlib/madlib/commit/e1199905ab2616df0d687c04372946d9477078ef). Let me know if they make sense to you and if you want more feedback before your PR will be merged. As the fixes are applied, I think it is ready to be merged.

Aaron

**Comment by adirastogi** [comment]
Thanks for the speedy review. I am glad to know that my code is up to 
the standards required by the project. I have to say that the excellent 
documentation on the contribution wiki helped me out a great deal .

I am okay with the fixes. I just wanted to get an opinion on whether the 
changes that I have made to the APIs are okay from a usability 
perspective and I have indicated as much on the comments there. 
Otherwise , I am fine with the PR to be merged.

Its great to know that my first contribution went well. I find the 
MADlib project very interesting and would like to continue to 
contribute, hopefully also as a summer intern under the GSoC programme, 
if MADlib is considering participating. I'll continue to look for areas 
where I feel I can contribute and also welcome any suggestions from the 
leads and the community.

Regards
Aditya

**Comment by haying** [comment]
The new APIs you added look fine. As Naive Bayes is still an early stage development module. We would  like to merge it as it stands and let the users give us feedback to decide things to be improved.

We have been helping GSoC on MADlib related projects. See [link](http://blog.pivotal.io/big-data-pivotal/features/pivotals-google-summer-of-code-2014-implementing-clustering-algorithms-in-madlib). Just let us know what we can help as you submit your proposal.

I am going to merge this PR after doing some more testing, probably today.

**Comment by haying** [comment]
Hi Aditya,

When I run tests on the new PR, there are some failures showing up and we have to fix them before we could close the PR. I am providing you the queries and datasets by email.

In Pivotal, we are running extensive tests again each MADlib module. We usually compare our results with output from R to make sure the answers are correct. If you would like your contribution to be tested and believed to be robust, we could work together to help you add the tests to compare with R. This would give developers and users confidence on the module and MADlib in general. We need the following 3 items:
1. SQL queries that use the new function and output the results
2. datasets needed in the queries (public, e.g. from UCI, or synthetic)
3. an R script that does the same computation as the new function
Note: We usually make use of PivotalR to read the same dataset from dataset to be consumed in R. If you are not familiar with R, we could help you convert the dataset.

In the email I am sending you, I will attach the 3 items and hope they can serve as an example if you like to add tests for naive bayes with continuous variables.

**Comment by adirastogi** [comment]
Hi Aaron,

Thanks for letting me know about this. I was kinda looking for a benchmark to do some more testing myself. Right now, the test cases that I have added are based on a dataset computed by hand. I did run my changes against the iris dataset from UCI and compared the classification results from scikit-learn.  But now that I know that I need to compare them against results from R, i can get on to it. 

I am not very familiar with R, but I am sure I can pick it up for the purposes of creating and running the testcases. I will take a look at the example that you have sent me later today and will let you know if I need some help with that.  

Best
Aditya

**Comment by adirastogi** [comment]
Hi Aaron,

I ran the three failing testcases that you shared and my latest commit takes care of the failures for the following 2 out of the 3 failing testcases:

-test_output_naive_bayes_create_view_1.sql
-test_output_naive_bayes_create_view_2.sql

The changes are a small modification of the edits that you made. Please let me know if these changes work in your test environment as well.

For the third test case, the parameters for the function are invalid. The way they have been provided in the testcase, they do not match any form of the create_nb_classify_view API. I tried running the testcase against a v1.7.1 build and it errors out there as well. I'll be sending you the modified test case file over e-mail that does not give an error. Could you please confirm if you see a similar behavior in your test environment ?

I tested the iris dataset from UCI with my changes and it seems to be producing the correct classification results when compared to R. However, I am still not able to understand how I can 'convert' the dataset to work with PivotalR. The R script I have currently reads data from a text file containing the iris dataset.  Could you share some information about how to set it up the way you have in your environment ? Also, If you have any datasets of your own that you would like me to try, please let me know and I can write tests for them as well.

Thanks
Aditya

**Comment by haying** [comment]
Hi Aditya,

I reviewed the changes and fixed the input test case. Could you share with me 1. the dataset (pg_dump to .sql format), 2. the query with all arguments you run, and 3. the R command on iris data? I will handle the rest and merge the code.

Thanks,
Aaron

**Comment by adirastogi** [comment]
Hi Aaron,

Thanks for the testing my changes. I am a little occupied this week, but 
I will be able to send these things to you on Friday evening or over the 
weekend. Please let me know if that is okay with you.

Thanks
Aditya

**Comment by haying** [comment]
Sounds good

**Comment by adirastogi** [comment]
Hi Aaron,

Please find attached the tarball that contains the following files which 
should help you run the iris dataset in your test environment:
- iris.data & iris_test.data : files containing test and training 
  datasets for the R script
- iris_data.sql & iris_test.sql : files containing test and training 
  datasets for the sql script
- new_naive_bayes.R : sql script that produces the classification 
  probabilities and classification results in the files
  iris_probs.ans and iris_class.ans respectively
  -iris_testcase.sql : sql commands to load the iris training and testing 
  datasets into database and run the newly    added APIs on them to 
  generate the classification and probability tables.

I have added some comments in the scripts to help you run them. I hope 
this will help you convert it into a test case. Do let me know if you 
need anything else in addition to these.

Best
Aditya

**Comment by haying** [comment]
Hi Aditya,

I don't see the attachment.

Regards,
Aaron

2015年2月1日日曜日、Aditya Rastoginotifications@github.comさんは書きました:

**Comment by adirastogi** [comment]
That's strange. I am attaching it again along with this email.

**Comment by haying** [comment]
Hi Aditya,

Thanks for the reply. I received your email this morning even though it was sent out on Sunday. It seems some email server delay was involved. Anyway, I got your files and will keep you updated.

Aaron

**Comment by haying** [comment]
Hi Aditya,

I run the testcase you built. The class output is correct but I have a question on the probability output. Output from MADlib does not exactly match R's. I wonder if that is what you expect.

For the data items with ID 86 and 87, the probability output from MADlib is:

```
madlib=# select * from iris_probs where key in (86, 87);
 key | class |        nb_prob        
-----+-------+-----------------------
  86 |     1 | 2.29345139327232e-202
  86 |     2 |     0.979425531542832
  86 |     3 |    0.0205744684571683
  87 |     1 | 4.81397918396811e-218
  87 |     2 |      0.93920449923663
  87 |     3 |    0.0607955007633697
(6 rows)
```

While R has

```
   classify_key            X1           X2           X3  
5            86 1.336526e-101 0.8734107 0.1265893
6            87 1.804796e-109 0.7971795 0.2028205
```

**Comment by adirastogi** [comment]
Hi Aaron,

That is odd. I tested it again on my build and the answers match. Are 
you sure you have pulled my latest changes ?  Also, I noticed that the 
iris_testcase.sql script that I sent you has a syntax error in the copy 
commands. Instead of

```
 copy iris from 'iris_data.sql' with delimiter ;
```

it should be

```
 copy iris from 'iris_data.sql' with delimiter ';' ;
```

But I guess you probably would have figured that out by now. If you are 
indeed running with the latest version of code from the gaussian_nb 
branch then please share the testcase files again with me ( including 
any changes that you made ) and I can run the same files again through 
my code.

Thanks
Aditya

**Comment by haying** [comment]
Hi Aditya,

It is matched after I tried again. My bad. Everything else looks good and I will merge your code soon.

Thanks,
Aaron

**Comment by haying** [comment]
Hi Aditya,

I added the test case you provided to install-check. I had to also add back the check for "array[]" otherwise Greenplum and HAWQ does not take it. See my commit: https://github.com/madlib/madlib/commits/gaussian_nb

Everything is green as it stands. I can merge it anytime if the new changes are fine with you.

In the future, if you'd like to download the 60-day trial version of Greenplum or HAWQ to test MADlib, you could sign up https://network.pivotal.io/

Thanks,
Aaron

**Comment by adirastogi** [comment]
Hi Aaron,

Thanks for taking the pains to test my code and incorporate the test 
cases. I am fine with the check for "array[]" . Do let me know if there 
is anything else that I need to do to get the code merged. Also, I would 
welcome any suggestions on what you would want me to work on next, as I 
would like to continue contributing.

Thanks,
Aditya

**Comment by haying** [comment]
Code is squashed and merged into master branch at [143c165ff4](https://github.com/madlib/madlib/commit/143c165ff44b26652249c6491cb7331e5704c0dc). Development branch is archived in a tag: [archive/gaussian_nb](https://github.com/madlib/madlib/commits/archive/gaussian_nb)

Thanks for your contribution, Aditya.

**Pull request closed without merging**
