### PR TITLE
Fixes for madlib-341/381/382

### PR DESCRIPTION
**Pull request by aojwang**
1. madlib-341: Check duplicated id values in training/classification table. (utility.sql_in).
2. madlib-381/382: Out of memory FOR C45_TRAIN on GPDB4.1. (decision_tree.sql_in).
3. Add an additional star (/**) to the classify, score, display, clean API.
4. Refine documentation for public API.

### CODE REVIEW

**Comment by cwelton** [comment]
I would be fine taking the fix for madlib-341, this looks low risk.  

However the fixes for madlib-381/382 are larger in scope than we can take at this stage in the release.  We do not have time to test and address any fallout from these changes.  Recommend waiting until after the release and inclusion in a later patch.

**Comment by aojwang** [comment]
Ok, i will create another pull request to include the fix for 341 and documentation issue.

**Comment by aojwang** [comment]
Hi Caleb,

If time is allowed, we still prefer to push the changes to the master. The reason is as following.
1) After the fixes, the node id will be changed and trained tree table will also be changed(jump column changed to lmc_nid and lmc_fval). Therefore, I think it's better to push to master, so that they look the same between this release and next release(patch) for dev users.  

2) No jump column (int[]) in trained tree any more, since its max size is equal to the number of distinct value of the best split feature represented by the row. We introduce two columns:  lmc_nid (leftmost child node id) and lmc_fval(the feature value which leads to the leftmost child node id). Other child nodes' ids can be deduced by lmc_nid and lmc)_fval, since the values for a feature and child nodes' ids are continuous. Therefore, most changes are related to change jump column to lmc_nid and lmc_fval although the fixes are large in scope. The risk should be low.

3) Delete some unnecessary code, such as reassign serial ids for tree node (__generate_final_tree). Now, it's very simple. Nodes' ids will not be changed. no aggregate functions to update lmc_nid and lmc_fval (just by simple SQL statement). Therefore, the risk should be low.

After discussed with Jiali, they may take 21 hours to run the minimum tests, and 29 hours for whole tests. Currently, they are working on k-means tests. Next night, they have time to run DT tests. We may get the result on Friday afternoon or next monday.

What do you think? thanks very much.

**Comment by cwelton** [comment]
Hard deadline is Thursday evening here, which gives aproximately 48 hours, this is not sufficient time to pull a change like this.

**Comment by aojwang** [comment]
Hi Caleb,

The pull request, https://github.com/madlib/madlib/pull/113, include all the bug fixes except for madlib-381/382. Thanks.

**Comment by cwelton** [comment]
Closing per discussion based on the understanding that this is included in later PR.

**Pull request closed without merging**
