### PR TITLE
Usability: Improved LMF output format

### PR DESCRIPTION
**Pull request by haying**
JIRA: MADLIB-578

After helping Sarah from the DS team to use this the first time, some usability is improved, mostly on making the output easier to be interpreted.

### CODE REVIEW

**Comment by haradh1** [comment]
Is this for v0.5?  Do we have a jira?

**Comment by haying** [comment]
I would count MADLIB-578 for this. Do we have to reopen it or create a new jira for this?

**Comment by haradh1** [comment]
I just wanted to make sure the status of this PR.  If you think it's worth recording additional changes as a history that we can look up later, go for jira.  Especially for bugs (, though I don't see this is a bug)

**Comment by haying** [comment]
This is more like making the feature complete than a bug. So I added 578 to the desc of this PR.

**Pull request closed without merging**
