### PR TITLE
This addresses Madlib 305

### PR DESCRIPTION
**Pull request by keesiong**

### CODE REVIEW

**Comment by fschopp** [comment]
Is this a superset of pull request 84?

**Comment by keesiong** [comment]
It's a subset. Pull request 84 also deals with madlib-257.
Once this is merged, I'll issue another PR to fix madlib-257.

**Comment by fschopp** [comment]
Hmm. All the upstream merges here and in pull request #84 make this quite confusing. If possible, please do not include upstream merges in pull requests. If you do need to include upstream changes while working on code, please rebase before starting a pull request.

**Comment by fschopp** [comment]
I'll do a cherry-pick now. Please do not base any work on your existing 'madlib-305' or 'master' branches, but reset your master branch to upstream/master before adding code. Thanks!

**Comment by fschopp** [comment]
Superseded by commit a92cc96.

**Pull request closed without merging**
