### PR TITLE
 SVM: Fix the SVM classification issue in parallel mode

### PR DESCRIPTION
**Pull request by renyi533**
Jira: Madlib-690
In parallel mode, classification/regression will fail if there is no data distributed to certain segments.
The root cause is that we always request a model for each segment. With this fix, we firstly check the data
distribution and omit the segments with no data.

### CODE REVIEW

**Comment by iyerr3** [comment]
Please update the commit messages as described in the contribution guide: https://github.com/madlib/madlib/wiki/Contribution-Guide . It would be helpful to have a description of the fix in the commit message.

**Comment by renyi533** [comment]
Thanks for your comments. I updated the commit message.

**Comment by iyerr3** [comment]
Everything looks good. I will merge this today.

**Comment by iyerr3** [comment]
Merged with commit: https://github.com/madlib/madlib/commit/a20fbcdbe2299f3962a7c713e5bae4fb00fc2d77

**Pull request closed without merging**
