### PR TITLE
fix madlib 474

### PR DESCRIPTION
**Pull request by renyi533**
Please see log below. The index of words should be in the range of [1, dict_size]. But some indexes are larger than 25335. This should be the root cause. The null value cannot fully resolve this issue. The macros, such as ARR_HASNULL, may generate wrong result.

I also provided a function named "check_array_null_elem" to accurately check the null element in array. 

testdb=# select count(*) from (select unnest(dict) from madlibtestdata.plda_nsf_abs_dict) l;
##  count 

 25335
(1 row)

testdb=# select \* from (select  unnest(contents) as widx from madlibtestdata.plda_nsf_abs_corpus) l where widx > 25335;
##  widx  

 27653
 26404
 27659
 29462
 28241
 29137
 29137
 25640
 25640
 25678
 25800
 25800
 30359

### CODE REVIEW

**Comment by haradh1** [comment]
If there could be such an array such that ARR_HASNULL () is bogus, that value is the problem.  I suggest exploring the reason for that.

Looking at your change, the original code didn't use ARR_HASNULL() but did ARR_NULLBITMAP(), which I think may be bogus.  ARR_HASNULL() check should have been done before ARR_NULLBITMAP()?

**Comment by renyi533** [comment]
Yes. It is not correct to use ARR_NULLBITMAP in the last commit. 

I see from the web that even ARR_HASNULL can generate wrong results.(I do not verify that ARR_HASNULL is wrong in some cases.) So I provided another function. Do you think we can totally rely on ARR_HASNULL? In this way, I can remove the function of check_array_null_elem and use ARR_HASNULL directly.

**Comment by haradh1** [comment]
If ARR_HASNULL return a wrong result, the entire backend code will break, even if you fixed it by your additional function.  So yes, it should be reliable.

**Comment by renyi533** [comment]
OK. I used the existing macros to detect null elements in array now. Please review again.

**Comment by haradh1** [comment]
So did you verify the latest fix with ARR_HASNULL passed the case described above?

**Comment by renyi533** [comment]
Yes. I verified this macro can work.

**Comment by haradh1** [comment]
Hmm, looking closer, I don't see why even ARR_NULLBITMAP doesn't work well.  For example. array_send() relies on ARR_NULLBITMAP returning NULL when the array doesn't contain NULL elements.  Can you describe more exactly what happens with that data?  What is returned from ARR_NULLBITMAP?  Why the array has bigger indices than its size?  Your test of

```
testdb=# select count(*) from (select unnest(dict) from madlibtestdata.plda_nsf_abs_dict) l;
```

should return the number of elements in plda_nsf_abs_dict, not the number of non-NULL elements, because the argument of count is asterisk.  Honestly I don't understand the connection between your fix and your explanation of what you observed.

**Comment by renyi533** [comment]
Hitoshi, can you turn online on the communicator? Or, can you tell me your phone number? I can call you immediately. I think this will be much more effective way.

**Comment by renyi533** [comment]
ARR_NULLBITMAP does not return NULL when the array doesn't contain NULL elements. It is incorrect for us to use it here.  Please see its definition. 

ARR_HASNULL works well during my test. But I read that even this macro can generate wrong results. So I originally add another function to check. But from your point, we should rely on existing macro. So I removed the function again.

Except for the NULL element problem, another issue is invalid range of work indexes. The sql you listed is for this separate issue. We should not mix them together.

**Comment by cwelton** [comment]
I'm fine with the new wording.  It sounds like we understand that the ARR_HASNULL vs ARR_NULLBITMAP change is not expected to change any behavior; in this case ARR_HASNULL is more semantically meaningful.

Looks good to pull.

**Comment by haradh1** [comment]
Pulled as it stands.

**Pull request closed without merging**
