### PR TITLE
Design document: The C++ Abstraction Layer

### PR DESCRIPTION
**Pull request by fschopp**
Jira: MADLIB-696

_Opening this pull request for visibility purposes. Please do not merge yet, I'll merge myself when ready._

### CODE REVIEW

**Comment by haying** [comment]
The old link madlib.net/design.pdf does not work. Is that expected?

**Comment by fschopp** [comment]
madlib.net/design works again. I currently don't know why the file disappeared on the server.

**Comment by fschopp** [comment]
@haying While updating the design document: Are you fine with being listed as author for the sections you wrote?

**Comment by haying** [comment]
Surely.

**Pull request merged**
